baseURL = "https://portfolio.tribouilloy.com/"
languageCode = "fr-fr"
title = "Florent Tribouilloy — Lead dev / CTO fractionné"
description = "Lead dev / CTO fractionné — Python & React. MVP SaaS, intégrations APIs, cloud, sécurité et mentoring pour startups."
theme = ["PaperMod"]
enableRobotsTXT = true


[params]
  defaultTheme = "auto"
  themeColor = "#22D3EE"
  ShowShareButtons = false
  ShowReadingTime = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = true
  disableThemeToggle = false
  hideFooter = true
  DateFormat = "2006-01-02"
  # Hero
  homeInfoParams = { Title = "Lead dev / CTO fractionné — Python & React", Content = "J’aide des startups early-stage à livrer un **MVP fiable** intégrant des **APIs externes** et prêt pour la **scalabilité**. \n\n👉 [Contactez-moi](mailto:tribouil@gmail.com) · [Malt](https://www.malt.fr/profile/florenttribouilloy) · [LinkedIn](https://www.linkedin.com/in/florenttribouilloy)" }


  socialIcons = [
    { name = "Malt", url = "https://www.malt.fr/profile/florenttribouilloy" },
    { name = "LinkedIn", url = "https://www.linkedin.com/in/florenttribouilloy" },
    { name = "GitHub", url = "https://github.com/tribouille" },
    { name = "Email", url = "mailto:tribouil@gmail.com" }
  ]

  images = ["og-default.svg"]

[params.assets]
  favicon = "favicon.ico"
  favicon16x16 = "favicon-16x16.png"
  favicon32x32 = "favicon-32x32.png"
  apple_touch_icon = "apple-touch-icon.png"
  safari_pinned_tab = "safari-pinned-tab.svg"

[outputs]
  home = ["HTML","RSS","JSON"]

[menu]
  [[menu.main]]
    name = "Projets"
    url = "/cases/"
    weight = 10
  [[menu.main]]
    name = "Offres"
    url = "/offers/"
    weight = 20
  [[menu.main]]
    name = "À propos"
    url = "/about/"
    weight = 30

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true